### ISSUE TITLE
DocList Depreciated

### ISSUE THREAD

**Issue by NathanJudson** [ahochsteger/gmail2gdrive#1]
Tried updating to DriveApp but has further issues with files and folders. 

It either creates a entirely new folder each time it runs or shows type error "TypeError: Cannot find function createFile in object folderAbc"

please help.

**Comment by ottonet** [comment]
Until @ahochsteger merges my PR, use code.gs from my fork at https://github.com/ottonet/gmail2gdrive

**Comment by ahochsteger** [comment]
I'm closing this issue since the PR https://github.com/ahochsteger/gmail2gdrive/pull/2 has already been merged for some time now.
