### ISSUE TITLE
Need to exclude signature images from attachments loop

### ISSUE THREAD

**Issue by aorborc** [ahochsteger/gmail2gdrive#13]
[Line 109](https://github.com/ahochsteger/gmail2gdrive/blob/master/Code.gs#L109) on Code.gs

var attachments = message.getAttachments();

It includes images that are included in the signature/inline

**Comment by ahochsteger** [comment]
@aorborc I'm not sure how to detect that the attached image is part of the signature. If you have an idea how to do that, let me know.

**Comment by aorborc** [comment]
@ahochsteger : I am [searching online](http://stackoverflow.com/questions/43000882/how-to-make-getattachments-in-gmailapp-to-exclude-images-from-signature) for a solution to exclude them. Looks like we need to find an enhancement request

**Comment by aorborc** [comment]
Update: It looks like GAppScript behavior. I have filed an [enhancement request](https://code.google.com/p/google-apps-script-issues/issues/detail?id=6866). Please star it.
