### ISSUE TITLE
Only save attachments from emails with a sepcific label?

### ISSUE THREAD

**Issue by baldybe** [ahochsteger/gmail2gdrive#20]
Hi,

I'm looking for an option to only save attachments from emails with a sepcific label.
Could you please advise how this could be achieved?

Thanks,

BB

**Comment by ahochsteger** [comment]
Hi,

yes, that is possible using "label:mylabel" as filter expression in the configuration.
You can use all search expressions supported by GMail as a filter (see: https://support.google.com/mail/answer/7190?hl=en).

Regards,
Andreas
