### ISSUE TITLE
Use label as new folder name

### ISSUE THREAD

**Issue by trevor3011** [ahochsteger/gmail2gdrive#27]
Hello, this looks like the perfect tool for what I need to do, I am a complete novice with Google Scripts so apologies if this is a very basic question!
The e-mails I need to filter will have user-defined labels attached, 'Save Attachments', and/or 'Save Mail' and will always have a label 'Job [jobname]'. I need to save the attachments and/or mail to my google drive folder [jobname] - i.e. the label name without the first 4 characters. That folder will already exist on google drive.
What changes do I need to make in the code and config to achieve this?
Many thanks for your help

**Comment by ahochsteger** [comment]
@trevor3011, could you solve your use case?
