### ISSUE TITLE
Global filter vs. Processing rules.

### ISSUE THREAD

**Issue by Austin-Chow** [ahochsteger/gmail2gdrive#30]
Hi, in the Config.gs file:
 
1. What is the difference between the "filter" variables in Processing rules and the "globalFilter" variable in Global filter?

2.  On line 8:  

"globalFilter": "-in:trash -in:drafts -in:spam",

Are you setting the global filter to NOT include messages in trash, drafts, AND spam? Lastly, do you know if Google Apps Scripts supports the 'and' operator: '&&' and 'AND'? 

Thank you!

**Comment by jowouters** [comment]
_globalFilter_ indeed is a filter that is used for all rules.  Per rule this globalFilter is combined with the _filter_ of that particular rule 
On top of that _processedLabel_ is used to further filter out already processed mails and _newerThan_ to select only newer mails. 

If these are the relevant lines in your config: 
```
"globalFilter": "-in:trash -in:drafts -in:spam",
"processedLabel": "to-gdrive/processed",
"newerThan": "1m",
"rules": [
(...)
"filter": "has:attachment subject:'[scanner]'"
(...)
```
the selection will be done using this selection: 

Processing rule:  
```
-in:trash -in:drafts -in:spam has:attachment subject:'[scanner]' -label:to-gdrive-processed newer_than:1m 
```

The filters do support both OR and AND.  See the example config for an example of OR
`"filter": "has:attachment (from:example3a@example.com OR from:example3b@example.com)",`

**Comment by ahochsteger** [comment]
Closing the issue since it's already excellently answered by @jowouters.
