### ISSUE TITLE
Publish the project

### ISSUE THREAD

**Issue by Phantom2017** [ahochsteger/gmail2gdrive#32]
Hi,
Sorry I'm new to Apps Scripts and I'm not sure how to publish the project to handle it to another user. Also, will this include the time-based trigger that I have created?
Thanks

**Comment by ahochsteger** [comment]
@Phantom2017, sorry for the really late reply, I'm answering nevertheless in case it's still of interest.
Currently the only way is to manually repeate the setup procedure from the documentation, copy the configuration and manually setup the time-based trigger.
In the future though (with the up-comming v2) I'm planning to provide it as Google Apps Script Library so you only have to take care of the configuration and not the code or time-based trigger anymore.
