### ISSUE TITLE
Archive Message After Processing

### ISSUE THREAD

**Issue by jhlee2222** [ahochsteger/gmail2gdrive#33]
I see it's possible to change the label which is applied after an email is processed. Is there a way to specify you would like it archived as well?

**Comment by rvbatista** [comment]
Yes, just use the rule archive!
      //  * archive (boolean, optional): Should the gmail thread be archived after processing? (default: false)

**Comment by ahochsteger** [comment]
Closing the issue since it has been alread answered by @rvbatista.
