### ISSUE TITLE
Saving Thread as PDF, in Addition to Attachments in the Same Folder

### ISSUE THREAD

**Issue by Hanshaw** [ahochsteger/gmail2gdrive#36]
Hello,

I believe there is an issue when attempting to convert the thread to a pdf and save it into the same folder as the attachments when they are stripped.

Here is my rule:

     {
        // Saves Attachments.
        "filter": "has:attachment",
        "saveThreadPDF": true,
        "folder": "'Testing/REQ-'yyyy-MM-dd-HH:mm:ss",
        "filenameTo": "'REQ-'yyyy-MM-dd'-T-'HH:mm:ss'-%s'",
        "archive": true
      }   

When this is executed it actually creates two folders, one for the attachments and one for the email that is converted to pdf.

The attachments go to a new folder such as: Testing/REQ-2020-04-01-08:28:32
On the other hand, the converted pdf goes to a new(different) folder: 'Testing/REQ-'yyyy-MM-dd-HH:mm:ss .  In addition, there is two copies of the email in the folder with the subject as the filename.

The goal would be to store everything in the same folder that is created.

**Comment by mrrosenthal85** [comment]
yes, this is important, how to achieve this?

**Comment by maxsnet** [comment]
I had this issue too so I fixed it in my patch that adds a log file, but you can do it directly like this:

In function **processThreadToPdf**, update rule.folder accordingly to remove all ' 

`replace(/\'/g,'')`

Check [https://regexr.com/](https://regexr.com/?368bu) to test RegEx, it is pretty cool :)

```

/**
* Generate a PDF document for the whole thread using HTML from .
 */
function processThreadToPdf(thread, rule) {
  Logger.log("INFO: Saving PDF copy of thread '" + thread.getFirstMessageSubject() + "'");
  rule.folder = rule.folder.replace(/\'/g,'');
  var folder = getOrCreateFolder(rule.folder);
  var html = processThreadToHtml(thread);
  var blob = Utilities.newBlob(html, 'text/html');
  var pdf = folder.createFile(blob.getAs('application/pdf')).setName(thread.getFirstMessageSubject() + ".pdf");
  f_addaline_log_file_SpreadsheetApp(thread.getFirstMessageSubject(),thread.getLastMessageDate(),thread.getId(),"https://mail.google.com/mail/u/0/#inbox/" + thread.getId(),"Thread",pdf.getName(),pdf.getUrl());
  return pdf;
}
```

**Comment by maxsnet** [comment]
Thinking about it, I didn't test if that bugs the regex replace with the date... can you tell me ?

**Comment by ahochsteger** [comment]
@maxsnet thanks for the contribution, is now committed to the master branch.
