### ISSUE TITLE
How to only add date ("YYYY-MM-DD_") as a file name prefix to the original attachment's file name

### ISSUE THREAD

**Issue by noarf** [ahochsteger/gmail2gdrive#50]
Hello,

First of all thanks for the great script! It works like a charm.

I'd like to rename attachments by simply adding a processing date prefix ('YYYY-MM-DD_') ; this prefix should only come as an addition to the original name and extension of the attachment which should both be preserved.
eg: 
original attachment name example : "originalname.pdf"
desired attachment new name: "YYYY-MM-DD_originalname.pdf'"

How can this be achieved?

Thanks a lot in advance for your help.

**Comment by noarf** [comment]
SOLVED

1- I modified Code.gs
`      else if (rule.filenameTo) {
        filename = Utilities.formatDate(messageDate, config.timezone, **rule.filenameTo.replace('%n',filename)**);`

2- and the rule in Config.gs accordingly
`        **"filenameTo": "yyyy-MM-dd_'%n'"**`

Works as desired (and explained above)

**Comment by ahochsteger** [comment]
@noarf, thanks for the contribution, it's now already in the codebase by merging PR #61 using `%o` as substitution parameter.
