### ISSUE TITLE
Doesnt process a message/attachment

### ISSUE THREAD

**Issue by dharshanduck** [ahochsteger/gmail2gdrive#62]
I sent a test attachment to the mailbox but it is only creating the label it is not however  creating/moving the attachment to the specified location in the drive folder.

Please do let me know what further information you would require to assist?

**Comment by ahochsteger** [comment]
@dharshanduck which version of gmail2gdrive did you use?
I'm specifically interested if the pull request I merged yesterday may have caused this issue.

**Comment by dharshanduck** [comment]
First was the version 4 commits behind master then the master

**Comment by dharshanduck** [comment]
Both had the same issue

**Comment by ahochsteger** [comment]
Can you share your configuration?

**Comment by dharshanduck** [comment]
The config file?

**Comment by ahochsteger** [comment]
The contents of `function getGmail2GDriveConfig() {...}` where the filter settings and processing rules are defined.
These control how your emails should be processed and which attachments should be stored in which folders of GDrive.
See <https://github.com/ahochsteger/gmail2gdrive#example-configuration> for an example.

**Comment by dharshanduck** [comment]
`/**
 * Configuration for Gmail2GDrive
 * See https://github.com/ahochsteger/gmail2gdrive/blob/master/README.md for a config reference
 */
function getGmail2GDriveConfig() {
  return {
    // Global filter
    "globalFilter": "-in:inbox",
    // Gmail label for processed threads (will be created, if not existing):
    "processedLabel": "to-gdrive/processed",
    // Sleep time in milli seconds between processed messages:
    "sleepTime": 100,
    // Maximum script runtime in seconds (google scripts will be killed after 5 minutes):
    "maxRuntime": 280,
    // Only process message newer than (leave empty for no restriction; use d, m and y for day, month and year):
    "newerThan": "1m",
    // Timezone for date/time operations:
    "timezone": "GMT",
    // Processing rules:
    "rules": [
      { // Store all attachments named "file.txt" from example4@example.com to the
        // folder "Examples/example4" and rename the attachment to the pattern
        "filter": "has:attachment from:REDACTED@gmail.com",
        "folder": "'test/test1'"
        
      }
    ]
  };
}`

**Comment by dharshanduck** [comment]
I figured out the issue it had to do with the "-" at the global filters

**Comment by dharshanduck** [comment]
3:33:52 AM	Notice	Execution started
3:33:48 AM	Info	INFO: Starting mail attachment processing.
3:33:49 AM	Info	INFO:   Processing rule: in:inbox has:attachment from:REDACTED@gmail.com -label:to-gdrive/processed newer_than:1m
3:33:49 AM	Info	INFO:     Processing thread: test3 (runtime: 0.202s/280s)
3:33:49 AM	Info	INFO:       Processing message: test3 (18157f9db2d8a6db)
3:33:49 AM	Info	INFO:         Processing attachment: csjtr.png
3:33:49 AM	Info	Saving to foldertest/test1
3:33:52 AM	Info	INFO: Finished mail attachment processing after 3.83s
3:33:57 AM	Notice	Execution completed

**Comment by ahochsteger** [comment]
The "-" in the filter means exclude messages that match the given filter.
It's documented here (search for "Remove messages from your results"): <https://support.google.com/mail/answer/7190?hl=en>
If I read your comments correctly you already could solve the issue by fixing the filter, right?

**Comment by dharshanduck** [comment]
Yep
