### ISSUE TITLE
Creates new parent folder if subfolder doesn't exist

### ISSUE THREAD

**Issue by kvolden** [ahochsteger/gmail2gdrive#7]
If a parent folder exists – let's call it 'abc' – and I write a rule in Config.gs which specifies a subfolder of this parent folder which does _not_ exist – let's call the non existing subfolder 'xyz' – the script creates a new parent folder with the same name as the old one, and puts the new subfolder with its files in this new parent folder.

How to recreate:
1: Manually, through the Drive web interface, create a root folder called 'abc'.
2: Create a rule in Config.gs with "folder": "abc/xyz".
3: Execute the script and make sure it hits an item described by the rule.

What I expect:
A newly created folder 'xyz' should be created under the existing folder 'abc'.

What happens:
Another root folder called 'abc' is created with the new subfolder 'xyz' and its file contents.

**Comment by mmitucha** [comment]
Hi,
I just ran into this issue and send pull request to trollkarlen2/gmail-rule-processor fork of this repo, which I used to fork the project (:

**Comment by cciprian5** [comment]
Corrected it here https://github.com/ahochsteger/gmail2gdrive/pull/9
The getFolders return a collection and not an array

**Comment by ahochsteger** [comment]
Closing the issue since the PR has already been merged.
