### ISSUE TITLE
Date format patterns for folder

### ISSUE THREAD

**Issue by kvolden** [ahochsteger/gmail2gdrive#8]
Would you consider adding the possibility to use date format patterns for folders as well? This would be very useful if one is saving attachments in a folder system reflecting the year or month the attachments were received.

**Comment by Dyllan42** [comment]
I don't suppose anyone has had any traction on this request.  I've been trying to figure out how to do this myself, but I'm stymied.

**Comment by cciprian5** [comment]
This is simple to be done. I've made the pull request https://github.com/ahochsteger/gmail2gdrive/pull/10

**Comment by ahochsteger** [comment]
Date format patterns for folder is now integrated.
Thanks for your suggestion, @kvolden, and your contribution, @cciprian5.

Regards,
Andreas
