### ISSUE TITLE
Trouble finding Lambda (parrent folder Id)

### ISSUE THREAD

**Issue by lewisbergman** [ahochsteger/gmail2gdrive#81]
So this isn't an issue with the code, just my ignorance of Google Drive. I think others may benefit from a better explanation of how to make this script work.. I propose explaining how to obtain the drive ID for a shared drive.
For instance, something like " Obtain the parentFolderId by opening the desired shared drive, and then clicking on parent of that drive. It is the random character string at the end of the URL and should look something like the following:
https://drive.google.com/drive/u/0/folders/0AAp0ay_HaKsQIK9DHB
The end of the URL is the parentFolderId which in this case would be 0AAp0ay_HaKsQIK9DHB. So the var would look like 
"parentFolderId": "0AAp0ay_HaKsQIK9DHB",

Maybe that is a bad idea but some help for the more novice would be appreciated. Once it is figured out, the script is amazing and greatly appreciated.

**Comment by ahochsteger** [comment]
It's now documented, thanks to @piraveen.
